name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #- name: configure
      #run: ./configure

    - name: Install dependencies
      working-directory: ./rag-app
      run: make install

    - name: Run tests
      working-directory: ./rag-app
      run: make test

    #- name: Run distcheck
    #  run: make distcheck
